<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219094013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course_offers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price DOUBLE PRECISION NOT NULL, is_negotiable BOOLEAN NOT NULL, message TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, course_id INT NOT NULL, chevalier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_747EC56A591CC992 ON course_offers (course_id)');
        $this->addSql('CREATE INDEX IDX_747EC56AC312EAF ON course_offers (chevalier_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, data JSON DEFAULT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE travel_announcements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_city VARCHAR(100) NOT NULL, departure_country VARCHAR(100) NOT NULL, arrival_city VARCHAR(100) NOT NULL, arrival_country VARCHAR(100) NOT NULL, travel_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_weight DOUBLE PRECISION NOT NULL, remaining_weight DOUBLE PRECISION NOT NULL, price_per_kg DOUBLE PRECISION NOT NULL, passport_path VARCHAR(255) NOT NULL, flight_ticket_path VARCHAR(255) NOT NULL, visa_path VARCHAR(255) DEFAULT NULL, boarding_pass_path VARCHAR(255) DEFAULT NULL, baggage_proof_path VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejected_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chevalier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE32403C312EAF ON travel_announcements (chevalier_id)');
        $this->addSql('ALTER TABLE course_offers ADD CONSTRAINT FK_747EC56A591CC992 FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_offers ADD CONSTRAINT FK_747EC56AC312EAF FOREIGN KEY (chevalier_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE travel_announcements ADD CONSTRAINT FK_7CE32403C312EAF FOREIGN KEY (chevalier_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE courses ADD recipient_last_name VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE courses ADD recipient_first_name VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE courses ADD recipient_phone VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE courses ADD delivery_token VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE courses ADD delivery_confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE courses ADD package_type VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE courses DROP price');
        $this->addSql('ALTER TABLE courses DROP is_negotiable');
        $this->addSql('UPDATE courses SET package_weight = NULL');
        $this->addSql('ALTER TABLE courses ALTER package_weight DROP DEFAULT');
        $this->addSql('ALTER TABLE courses ALTER package_weight TYPE DOUBLE PRECISION USING package_weight::double precision');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A9A55A4C4F3C47A9 ON courses (delivery_token)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE course_offers DROP CONSTRAINT FK_747EC56A591CC992');
        $this->addSql('ALTER TABLE course_offers DROP CONSTRAINT FK_747EC56AC312EAF');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE travel_announcements DROP CONSTRAINT FK_7CE32403C312EAF');
        $this->addSql('DROP TABLE course_offers');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE travel_announcements');
        $this->addSql('DROP INDEX UNIQ_A9A55A4C4F3C47A9');
        $this->addSql('ALTER TABLE courses ADD price DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE courses ADD is_negotiable BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE courses DROP recipient_last_name');
        $this->addSql('ALTER TABLE courses DROP recipient_first_name');
        $this->addSql('ALTER TABLE courses DROP recipient_phone');
        $this->addSql('ALTER TABLE courses DROP delivery_token');
        $this->addSql('ALTER TABLE courses DROP delivery_confirmed_at');
        $this->addSql('ALTER TABLE courses DROP package_type');
        $this->addSql('ALTER TABLE courses ALTER package_weight TYPE VARCHAR(20)');
    }
}
