<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122102804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chevalier_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(50) NOT NULL, nationality VARCHAR(10) NOT NULL, city VARCHAR(255) DEFAULT NULL, message TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, admin_notes TEXT DEFAULT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_by_id INT DEFAULT NULL, created_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C80E2F032FFD4FD3 ON chevalier_requests (processed_by_id)');
        $this->addSql('CREATE INDEX IDX_C80E2F03E104C1D3 ON chevalier_requests (created_user_id)');
        $this->addSql('ALTER TABLE chevalier_requests ADD CONSTRAINT FK_C80E2F032FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chevalier_requests ADD CONSTRAINT FK_C80E2F03E104C1D3 FOREIGN KEY (created_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chevalier_requests DROP CONSTRAINT FK_C80E2F032FFD4FD3');
        $this->addSql('ALTER TABLE chevalier_requests DROP CONSTRAINT FK_C80E2F03E104C1D3');
        $this->addSql('DROP TABLE chevalier_requests');
    }
}
