<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123102200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, participant1_id INT NOT NULL, participant2_id INT NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2521BF1B29A9963 ON conversations (participant1_id)');
        $this->addSql('CREATE INDEX IDX_C2521BF1A02F368D ON conversations (participant2_id)');
        $this->addSql('CREATE INDEX IDX_C2521BF1591CC992 ON conversations (course_id)');
        $this->addSql('CREATE TABLE messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, type VARCHAR(20) NOT NULL, proposed_price DOUBLE PRECISION DEFAULT NULL, offer_status VARCHAR(20) DEFAULT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E969AC0396 ON messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id)');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1B29A9963 FOREIGN KEY (participant1_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1A02F368D FOREIGN KEY (participant2_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1591CC992 FOREIGN KEY (course_id) REFERENCES courses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1B29A9963');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1A02F368D');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1591CC992');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E969AC0396');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F624B39D');
        $this->addSql('DROP TABLE conversations');
        $this->addSql('DROP TABLE messages');
    }
}
